### ISSUE TITLE
Still requiring running of lb-services on fresh install

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#173]
It would appear some things are still missing and require lb-services command still be executed on a fresh install to put everything in order.  If you don't run lb-services and try to hit the main web page for the server you get the following error in the console on the server when the client attempts to connect:
`
Error: Cannot GET /js/lb-services.js
    at raiseUrlNotFoundError (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request] (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/node_modules/serve-static/index.js:120:7)
    at SendStream.emit (events.js:107:17)
    at SendStream.error (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/node_modules/send/index.js:245:17)
    at SendStream.onStatError (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/node_modules/send/index.js:356:12)
`
However if you run lb-services then hit the site from the client all seems to work ok.

**Comment by michaelsframe** [comment]
Which branch was this on?  Can you test on Develop and confirm still occurring?
